<template>
<div class="loadingio-spinner-gear-kelp3qfpjbp"><div class="ldio-alx90opm0se">
<div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div></div>


</template>
<script>
export default {
    
}
</script>
<style type="text/css">
@keyframes ldio-alx90opm0se {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(22.5deg) }
  100% { transform: rotate(45deg) }
}
.ldio-alx90opm0se > div {
  transform-origin: 50px 50px;
  animation: ldio-alx90opm0se 0.2s infinite linear;
}
.ldio-alx90opm0se > div div {
    position: absolute;
    width: 11px;
    height: 76px;
    background: #a12d2b;
    left: 50px;
    top: 50px;
    transform: translate(-50%,-50%);
}
.ldio-alx90opm0se > div div:nth-child(1) {
    width: 60px;
    height: 60px;
    border-radius: 50%;
}
.ldio-alx90opm0se > div div:nth-child(6) {
    width: 40px;
    height: 40px;
    background: #bd9d91;
    border-radius: 50%;
}.ldio-alx90opm0se > div div:nth-child(3) {
  transform: translate(-50%,-50%) rotate(45deg)
}.ldio-alx90opm0se > div div:nth-child(4) {
  transform: translate(-50%,-50%) rotate(90deg)
}.ldio-alx90opm0se > div div:nth-child(5) {
  transform: translate(-50%,-50%) rotate(135deg)
}
.loadingio-spinner-gear-kelp3qfpjbp {
  width: 75px;
  height: 75px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-alx90opm0se {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.75);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-alx90opm0se div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>